name: device-login-test

on:
 workflow_dispatch:

jobs:
 main-job:

  runs-on: ubuntu-20.04

  steps:

   - name: az login with device code
     run: az login --use-device-code
    
   - name: call Microsoft Graph via az rest 
     run: az rest --method GET --url https://graph.microsoft.com/v1.0/me --resource https://graph.microsoft.com
