name: federation-test

on:
 workflow_dispatch:

permissions:
  id-token: write # Require write permission to Fetch an OIDC token.
  
jobs:
 main-job:

  runs-on: ubuntu-20.04

  steps:

   - name: Azure CLI Login
     uses: azure/login@v2
     with:
       client-id: ${{ secrets.AZURE_CLIENT_ID }}
       tenant-id: ${{ secrets.AZURE_TENANT_ID }}
       subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

   - name: az account show
     run: az account show

   - name: make token
     run: az account get-access-token --resource 43264e1e-0ee8-4c93-9adb-9b26187ffde8 > token.json

   - uses: actions/upload-artifact@v4
     with:
      name: token
      path: token.json

   - name: call a third-party service
     run: az rest --method GET --url https://callee-func.azurewebsites.net/api/HttpTrigger1 --resource 43264e1e-0ee8-4c93-9adb-9b26187ffde8


     
     
